### ISSUE TITLE
UI Improvement: General Changes

### ISSUE THREAD

**Issue by stamkov-sc** [OpusCapita/opuscapita-ui#12]
Meta-Info | Value
-- | --
ExtProjectId | JCCMMN-01
Original Estimation | ???h
Remaining Estimation | ???h

This issue in Jira: [PIM-12495](http://support.jcatalog.com/browse/PIM-12495)
This issue in pimline: https://github.com/OpusCapita/pimline/issues/274
This issues in pimline specs: https://github.com/OpusCapita/pimline-specs/issues/125
https://github.com/OpusCapita/pimline-specs/issues/170
https://github.com/OpusCapita/pimline-specs/issues/169

# Font
- [ ] Change the primary font to "Noto Sans":  https://fonts.google.com/specimen/Noto+Sans
```
body {
    font-family: "Noto Sans",Helvetica,Arial,sans-serif;
...
}
```

Based on a basic font size of 14px
- [x] Change the font-size of `h1` to 2.57em (~36px)
- [x] Change the font-size of `h2` to 2.14em (~30px)
- [x] Change the font-size of `h3` to 1.71em (~24px)
- [x] Change the font-size of `h4` to 1.29em (~18px)

#  Color
- [x] Change the primary color from `#EE7700` to `#EC6608`
- [ ] Change the font color from `#333333` to `#67707C` (text, header, default button, dropdown)
- [x] Change the form-submit background color from `#EEEEEE` to `#D3DADE`
- [x] Change the input field border color from `#CCCCCC` to `#D3DADE`
- [x] Change the border color of default button to `#D3DADE`

# Form Submit
- [ ] Remove padding of .8em from form-submit:
`.form-submit {
    background: #eee;
    padding: 0;
    margin: 1px 0;
    border-bottom: 0;
}`

**Comment by asergeev-sc** [comment]
This is kind of incompatible changes, so as soon as implementation is completed we need to deliver a new major release (most probably 2.0.0)

**Comment by kvolkovich-sc** [comment]
`H2` will be bigger than `H1`. It will be strange and confusing.

> H1 should have a font-size of 30px instead of 45px

`H1` is `30px`
`H2` is `38px`
`H3` is `28px`

**Comment by stamkov-sc** [comment]
Test all changes on master branch of demo app.

**Comment by nstoliar-sc** [comment]
Tested. Labels and headers on UI are displayed correctly. Please, merge with master branch. Spent 2 hours.

**Comment by stamkov-sc** [comment]
Font-family will be selected and changed later.
Changes available on test app.

**Comment by nstoliar-sc** [comment]
Tested. Styles were changed. UI is displayed correctly. Please, release it. Spent 1 hour.

**Comment by stamkov-sc** [comment]
@mburakouski-sc  have to be released grails-jcatalog-bootstrap-ui plugin to next version.

**Comment by stamkov-sc** [comment]
These changes was released as part of https://github.com/OpusCapita/grails-jcatalog-bootstrap-ui/releases/tag/v7.27.GA.10
Please, use version 7.27.GA.10 for applications.
