### ISSUE TITLE
Extract variables from navigation extension to customized variables.less

### ISSUE THREAD

**Issue by ddivin-sc** [OpusCapita/opuscapita-ui#20]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01
Original Estimation | 3h
Remaining Estimation | ???h

Description
---

Following variables should be extracted from `extensions/navigation/opuscapita-dark.less`
to `extensions/navigation/variables.less`
```
@navigation-bg: #3b4a56;
@navigation-text-color: #fff;
@navigation-notification-text-color: #fff;
@navigation-notification-bg-color: #ec6608;
@navigation-item-active-border-color: #ec6608;
@navigation-item-vertical-active-bg-color: @navigation-item-active-border-color;

@color-warning: #ec6608;
@color-success: #3aa57b;
@color-info: #67707c;
@color-error: #dd2515;
```
The variables like `@color-warning` should be renamed to `@navigation-color-warning`

As the result this variables will be processing with document less service, so you need to describe all variables with commentaries and section in special convention for UI representation, like it's done in Bootstrap variables, for example:
```
//== Typography
//
//## Font, line-height, and color for body text, headings, and more.

@font-family-sans-serif:  "Helvetica Neue", Helvetica, Arial, sans-serif;
@font-family-serif:       Georgia, "Times New Roman", Times, serif;
//** Default monospace fonts for `<code>`, `<kbd>`, and `<pre>`.
@font-family-monospace:   Menlo, Monaco, Consolas, "Courier New", monospace;
@font-family-base:        @font-family-sans-serif;
```

Original issue: https://github.com/OpusCapita/minsk-core-externals/issues/476

**Comment by ddivin-sc** [comment]
For QA: you can check it on https://demo.core.dev.opuscapita.com/minsk-core-demo/bootstrap-ui-cust-issue-3
Please, check following next cases:
1. Updating background color for navigation in theme editor
2. Updating background color for navigation in customization area
3. Updating background color for navigation in theme editor and customization area

**Comment by ddivin-sc** [comment]
Please, review my code.

**Comment by nstoliar-sc** [comment]
Tested with https://github.com/OpusCapita/grails-sap-master-data-import/issues/1. Navigation variables settings could be made via theme editor or customization area (`webapp/plugins/styles/less/theme/<theme name>/variables.less` file). Please, merge with master branch.
