### ISSUE TITLE
Improve styles for OPC shopping cart

### ISSUE THREAD

**Issue by stamkov-sc** [OpusCapita/opuscapita-ui#23]
Meta-Info | Value
-- | --
ExtProjectId | JCOPC-01
Original Estimation | 1h
Remaining Estimation | ???h

Original issue https://support.jcatalog.com/browse/OPC-14242

**Comment by asergeev-sc** [comment]
New release of jCatalog Bootstrap UI plugin is available [7.27.GA.18](https://github.com/OpusCapita/grails-jcatalog-bootstrap-ui/releases/tag/v7.27.GA.18)
